[project]
name = "minimal_theme"
description = "a minimal sphinx theme for the documentation"
requires-python = ">=3.7"
version = "2024.10.08"

[project.entry-points."sphinx.html_themes"]
name_of_theme = "minimal_theme"